
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openInput(name: string) : Promise<void> {
    await TAURI_INVOKE("plugin:midi|open_input", { name });
},
async closeInput(name: string) : Promise<void> {
    await TAURI_INVOKE("plugin:midi|close_input", { name });
},
async openOutput(name: string) : Promise<void> {
    await TAURI_INVOKE("plugin:midi|open_output", { name });
},
async closeOutput(name: string) : Promise<void> {
    await TAURI_INVOKE("plugin:midi|close_output", { name });
},
async outputSend(name: string, msg: number[]) : Promise<void> {
    await TAURI_INVOKE("plugin:midi|output_send", { name, msg });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
midiMessage: MIDIMessage,
stateChange: StateChange
}>({
midiMessage: "plugin:midi:midi-message",
stateChange: "plugin:midi:state-change"
})

/** user-defined constants **/



/** user-defined types **/

export type MIDIMessage = [string, number[]]
export type StateChange = { inputs: string[]; outputs: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
